dashboard_id: daily_sales
generated_at: '2026-04-30T16:22:49'
cards:
- cd_id: k02a7d3097d94489381bbed7
  cd_type: CHART
  name: skc排名
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - skc编码
  - 照片
  - 波段
  - 产品线
  - 吊牌价
  - T+1销售_金额
  - T+1销售_件数
  - T+1销售_折扣
  - 历史销售件数_近7天
  - 历史销售件数_累销
  - 周转率_有销店数
  - 周转率_投放店数
  - 周转率_店动销
  - 周转率_店存
  - 周转率_店存周转周
  - 周转率_店存消化率
  row_count: 10
  key: skcTop10
- cd_id: peaee175ceeb24483995edf1
  cd_type: CHART
  name: 城市
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 渠道
  - 城市
  - 正价_业绩
  - 正价_店数
  - 正价_店均业绩
  - 正价_UPT
  - 正价_店均单数
  - 正价_客单价
  - 正价_入机折扣
  - 正价_实销折扣
  - 奥莱_业绩
  - 奥莱_店数
  - 奥莱_店均业绩
  - 奥莱_UPT
  - 奥莱_店均单数
  - 奥莱_客单价
  - 奥莱_入机折扣
  - 奥莱_实销折扣
  row_count: 46
  key: dailySalesOverview
- cd_id: c1c8c6067cae54b50a26e51f
  cd_type: CHART
  name: 正价店
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 门店
  - 业绩
  - UPT
  - 单数
  - 客单价
  - 入机折扣
  - 实销折扣
  row_count: 75
  key: storeDetailRegular
- cd_id: ed3661a8128c6449bac31d3e
  cd_type: CHART
  name: 奥莱店
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 门店
  - 业绩
  - UPT
  - 单数
  - 客单价
  - 入机折扣
  - 实销折扣
  row_count: 23
  key: storeDetailOutlet
- cd_id: va60ffe8f39e94e2db7d1917
  cd_type: CHART
  name: 策略结构
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 渠道
  - 城市
  - 正价_扣券占比_当年正价
  - 正价_扣券占比_当年活动
  - 正价_扣券占比_住年旧货
  - 正价_实销折损_当年正价
  - 正价_实销折损_当年活动
  - 正价_实销折损_住年旧货
  - 奥莱_扣券占比_当年正价
  - 奥莱_扣券占比_当年活动
  - 奥莱_扣券占比_住年旧货
  - 奥莱_实销折损_当年正价
  - 奥莱_实销折损_当年活动
  - 奥莱_实销折损_住年旧货
  row_count: 44
  key: salesTrend
- cd_id: l629aae53e1a048439098814
  cd_type: CHART
  name: 正价_店铺明细
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 店铺
  - 占比_当年正价
  - 占比_当年活动
  - 占比_住年旧货
  - 实销折损_当年正价
  - 实销折损_当年活动
  - 实销折损_住年旧货
  row_count: 75
  key: storeTrendRegular
- cd_id: bec6fabc41c3741278056110
  cd_type: DRILL
  name: 2025-11-11 11:47:09-drill-正价排名
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 店铺
  - 件数
  - 店存
  row_count: 99
  key: drillSkcRankingStore
- cd_id: tfcce89fce25d49cbafd59be
  cd_type: CHART
  name: 奥莱_店铺明细
  collect: true
  skip: false
  collect_strategy: single
  columns:
  - 店铺
  - 占比_当年正价
  - 占比_当年活动
  - 占比_住年旧货
  - 实销折损_当年正价
  - 实销折损_当年活动
  - 实销折损_住年旧货
  row_count: 23
  key: storeTrendOutlet
- cd_id: ab3ced129fcda47058666dab
  cd_type: CHART
  name: 正价_销售占比
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 新/旧货分类
  - 销售占比%
  row_count: 3
  key: ab3ced129fcda47058666dab
- cd_id: j4045eba2dd2e4db69f06b26
  cd_type: CHART
  name: 奥莱店_销售占比
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 新/旧货
  - 销售扣券%
  row_count: 3
  key: j4045eba2dd2e4db69f06b26
- cd_id: kc8e56cd6f4e54d49b5e5736
  cd_type: CHART
  name: 正价店_类别
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 维度_类别
  - 销售%
  - 吊牌%
  - 总进%
  row_count: 9
  key: kc8e56cd6f4e54d49b5e5736
- cd_id: me44720f2e8974152bb011d5
  cd_type: CHART
  name: 正价店_波段
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 年份类型
  - 维度_波段
  - 销售%
  - 吊牌%
  - 总进%
  row_count: 12
  key: me44720f2e8974152bb011d5
- cd_id: ma8e0221acd4f44c29a0d0e9
  cd_type: CHART
  name: 奥莱店_类别
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 维度_类别
  - 销售%
  - 吊牌%
  - 总进%
  row_count: 9
  key: ma8e0221acd4f44c29a0d0e9
- cd_id: w528fc2f5c1ce429d92fb1ca
  cd_type: CHART
  name: 奥莱店_波段
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 年份类型
  - 维度_波段
  - 销售%
  - 吊牌%
  - 总进%
  row_count: 12
  key: w528fc2f5c1ce429d92fb1ca
- cd_id: a080df2142d7745fb906fbe9
  cd_type: CHART
  name: 奥莱店_货期
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 维度_货期
  - 销售扣券%
  row_count: 5
  key: a080df2142d7745fb906fbe9
- cd_id: g7ef11975fa074e5cb6d68e4
  cd_type: CHART
  name: 正价店_货期
  collect: true
  skip: false
  collect_strategy: split_by_filter
  columns:
  - 维度_货期
  - 销售扣券%
  row_count: 5
  key: g7ef11975fa074e5cb6d68e4
